### ISSUE TITLE
name in poetry file inconsistent with module name

### ISSUE THREAD

**Issue by 0liverCrosby** [mjjq/python-intermediate-inflammation#11]
Either change the name of the module, or the name in the poetry project.toml file so that they are the same

https://github.com/mjjq/python-intermediate-inflammation/blob/9b05e0a6e84d04d3d3e8917c9ae38dd3ebb95e98/pyproject.toml#L2

**Comment by mjjq** [comment]
See #12

**Comment by mjjq** [comment]
Fixed in #13
