### ISSUE TITLE
test_models.py fails

### ISSUE THREAD

**Issue by pjc667** [mjjq/python-intermediate-inflammation#6]
ModuleNotFoundError: No module named 'numpy'

**Comment by rk-8194** [comment]
Works fine for me (I have numpy on my base environment). Maybe packaging the program so we can install dependencies automatically will fix this. ( see #4 )

**Comment by mjjq** [comment]
Merged `develop` into `main`, could you test this @FusionMusic ?

**Comment by FusionMusic** [comment]
Fixed in #13
